"""
agents/taxonomy_agent.py - Taxonomy management Agent

Responsibilities:
1. Initialize taxonomy from existing surveys/classic works
2. Dynamically update taxonomy as papers are added
3. Assign new papers to existing categories
4. Propose taxonomy change proposals (mark major category changes for human confirmation)

Human-in-the-loop:
- Minor updates (BALANCED mode): executed automatically
- Major category updates (BALANCED mode): fill pending_taxonomy_update,
  triggering interrupt() in workflow/nodes.py's taxonomy_review_node
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from survey_agent.interfaces.llm import LLMProvider
from survey_agent.state import TaxonomySensitivity
from survey_agent.utils.paper_card import PaperCard
from survey_agent.utils.taxonomy import Taxonomy, TaxonomyManager

logger = logging.getLogger(__name__)

_PROMPT_DIR = Path(__file__).parent.parent.parent.parent / "prompts"


class TaxonomyAgent:
    """
    Taxonomy construction and maintenance Agent.

    Core responsibilities:
    - Recommend categories for new papers
    - Propose taxonomy updates (add/split/merge categories)
    - Collaborate with users to maintain taxonomy consistency
    """

    def __init__(self, llm: LLMProvider) -> None:
        self._llm = llm
        self._suggest_prompt = self._load_prompt("taxonomy_suggest.md")

    def _load_prompt(self, filename: str) -> str:
        path = _PROMPT_DIR / filename
        if path.exists():
            return path.read_text(encoding="utf-8")
        return ""

    async def initialize_taxonomy(
        self,
        topic: str,
        paper_notes: list[str],
        existing_surveys: list[dict[str, Any]],
        user_defined: dict[str, Any] | None = None,
    ) -> Taxonomy:
        """
        Initialize the taxonomy skeleton.

        Priority: user-predefined taxonomy > inferred from existing survey chapter structure >
        automatically generated by LLM based on paper notes.

        Args:
            topic: Survey topic
            paper_notes: List of existing paper notes
            existing_surveys: Found survey papers (used to borrow their taxonomy)
            user_defined: User-predefined taxonomy dict (if any)

        Returns:
            Initialized Taxonomy object
        """
        if user_defined and user_defined.get("categories"):
            logger.info("Using user-predefined taxonomy")
            return Taxonomy.from_dict(user_defined)

        # Extract possible taxonomy information from survey abstracts
        survey_context = "\n".join(
            f"- {s.get('title', '')}: {(s.get('abstract') or '')[:200]}"
            for s in existing_surveys[:5]
        )

        notes_sample = "\n\n".join(paper_notes[:20]) if paper_notes else "No paper notes available yet"

        prompt = f"""Survey topic: {topic}

Related surveys (for reference on their classification frameworks):
{survey_context or "No related surveys found"}

Sample paper notes (first 20 papers):
{notes_sample}

Please design a reasonable taxonomy framework (3-6 major categories) for this survey. Output JSON:
{{
  "version": 1,
  "categories": [
    {{
      "id": "cat_01",
      "name": "Major category name",
      "description": "What content this category covers",
      "parent_id": null,
      "paper_ids": [],
      "subcategories": [
        {{
          "id": "cat_01_01",
          "name": "Subcategory name",
          "description": "Subcategory description",
          "parent_id": "cat_01",
          "paper_ids": [],
          "subcategories": []
        }}
      ]
    }}
  ],
  "changelog": ["v1: initial taxonomy"]
}}

Output only JSON, no other text.
"""
        response = await self._llm.expensive_complete(
            [{"role": "user", "content": prompt}],
            max_tokens=4096,
        )

        try:
            start = response.find("{")
            end = response.rfind("}") + 1
            if start >= 0 and end > start:
                tax_dict = json.loads(response[start:end])
                return Taxonomy.from_dict(tax_dict)
        except (json.JSONDecodeError, ValueError, KeyError) as e:
            logger.warning(f"Taxonomy initialization parsing failed: {e}, using empty taxonomy")

        return Taxonomy.empty()

    async def assign_papers_to_categories(
        self,
        papers: list[PaperCard],
        taxonomy: Taxonomy,
        topic: str,
    ) -> dict[str, list[str]]:
        """
        Batch-assign a list of papers to taxonomy nodes.

        Args:
            papers: List of papers to assign
            taxonomy: Current taxonomy
            topic: Survey topic

        Returns:
            {category_id: [paper_id, ...]} assignment results
        """
        if not papers or not taxonomy.categories:
            return {}

        manager = TaxonomyManager(taxonomy)
        all_cats = manager.get_all_categories_flat()

        cats_desc = "\n".join(
            f"- {cat.id}: {cat.name} — {cat.description}"
            for cat in all_cats
        )

        papers_desc = "\n".join(
            f"- {p.s2_paper_id}: \"{p.title}\" ({p.year}) | Contributions: {'; '.join(p.key_contributions[:2])}"
            for p in papers[:50]
        )

        prompt = f"""Survey topic: {topic}

Taxonomy nodes:
{cats_desc}

Papers to assign (each paper can be assigned to multiple categories):
{papers_desc}

Output JSON assigning each paper to the best-matching categories (paper_id -> list of category_ids):
{{
  "paper_id_1": ["cat_01", "cat_02_01"],
  "paper_id_2": ["cat_02"],
  ...
}}

Output only JSON, no other text.
"""
        response = await self._llm.cheap_complete(
            [{"role": "user", "content": prompt}],
            max_tokens=3000,
        )

        try:
            start = response.find("{")
            end = response.rfind("}") + 1
            if start >= 0 and end > start:
                assignments = json.loads(response[start:end])
                # Invert: category_id -> [paper_id]
                result: dict[str, list[str]] = {}
                for pid, cat_ids in assignments.items():
                    for cid in cat_ids:
                        result.setdefault(cid, []).append(pid)
                return result
        except (json.JSONDecodeError, ValueError) as e:
            logger.warning(f"Paper assignment parsing failed: {e}")

        return {}

    async def propose_taxonomy_update(
        self,
        new_papers: list[PaperCard],
        current_taxonomy: Taxonomy,
        topic: str,
        sensitivity: str = TaxonomySensitivity.BALANCED,
    ) -> dict[str, Any] | None:
        """
        Assess whether taxonomy needs updating based on new papers and propose a change.

        Args:
            new_papers: New batch of papers
            current_taxonomy: Current taxonomy
            topic: Survey topic
            sensitivity: Update sensitivity

        Returns:
            Update proposal dict (None if no update needed):
            {
                "type": "add_major|add_sub|rename|split",
                "is_major_change": bool,
                "description": "Change description",
                "proposed_change": {...},
                "reason": "Reason for the proposal"
            }
        """
        if len(new_papers) < 3:
            return None  # Too few papers to assess

        # In STRICT mode all changes require human confirmation
        if sensitivity == TaxonomySensitivity.STRICT:
            pass  # Continue generating proposal, but mark all as is_major_change=True

        manager = TaxonomyManager(current_taxonomy)
        current_cats = "\n".join(
            f"- {cat.id}: {cat.name} ({len(cat.paper_ids)} papers)"
            for cat in manager.get_all_categories_flat()
        )

        new_titles = "\n".join(f"- {p.title}" for p in new_papers[:20])

        prompt = f"""Survey topic: {topic}

Current taxonomy:
{current_cats}

Newly added papers:
{new_titles}

Please determine whether the taxonomy needs updating (adding categories, splitting existing categories, etc.).

If an update is needed, output a JSON proposal:
{{
  "type": "add_major|add_sub|rename|split|none",
  "is_major_change": true|false,
  "description": "One-sentence description of the change",
  "proposed_change": {{
    "action": "Specific operation description",
    "target_category_id": "Related category ID (optional)",
    "new_category_name": "New category name (if creating)",
    "new_category_description": "New category description"
  }},
  "reason": "Why this change is needed"
}}

If no update is needed, output: {{"type": "none"}}

Output only JSON.
"""
        response = await self._llm.cheap_complete(
            [{"role": "user", "content": prompt}],
            max_tokens=1024,
        )

        try:
            start = response.find("{")
            end = response.rfind("}") + 1
            if start >= 0 and end > start:
                proposal = json.loads(response[start:end])
                if proposal.get("type") == "none":
                    return None

                # STRICT mode: mark all changes as major
                if sensitivity == TaxonomySensitivity.STRICT:
                    proposal["is_major_change"] = True

                return proposal
        except (json.JSONDecodeError, ValueError):
            pass

        return None

    def apply_taxonomy_update(
        self,
        taxonomy: Taxonomy,
        proposal: dict[str, Any],
    ) -> Taxonomy:
        """
        Apply an approved update proposal to the taxonomy.

        Args:
            taxonomy: Current taxonomy
            proposal: Proposal returned by propose_taxonomy_update

        Returns:
            Updated taxonomy
        """
        manager = TaxonomyManager(taxonomy)
        change = proposal.get("proposed_change", {})
        change_type = proposal.get("type", "none")

        if change_type == "add_major":
            manager.add_major_category(
                name=change.get("new_category_name", "New Category"),
                description=change.get("new_category_description", ""),
            )
        elif change_type == "add_sub":
            manager.add_subcategory(
                parent_id=change.get("target_category_id", ""),
                name=change.get("new_category_name", "New Subcategory"),
                description=change.get("new_category_description", ""),
            )
        elif change_type == "rename":
            manager.rename_category(
                category_id=change.get("target_category_id", ""),
                new_name=change.get("new_category_name", ""),
            )
        else:
            logger.warning(f"Unknown change type: {change_type}")

        return manager.taxonomy
